
((digest . "d9f439704f9afcfaa7c29329d08467d2") (undo-list nil ("      campaign:
        id: ID
        url: キャンペーンリンクURL
        image_url_s: 画像URL小(608x228)
        image_url_m: 画像URL中(712x267)
        image_url_l: 画像URL大(1180x442)
" . 298) ((marker . 1586) . -16) ((marker . 1586) . -16) ((marker . 1540) . -31) ((marker . 1540) . -31) ((marker . 1518) . -57) ((marker . 1518) . -57) ((marker . 1489) . -94) ((marker . 1489) . -94) ((marker . 1469) . -131) ((marker . 1469) . -131) ((marker . 1454) . -169) ((marker . 1454) . -169) ((marker . 298) . -169) ((marker . 298) . -169) ((marker . 298) . -169) ((marker . 298) . -169) ((marker) . -169) ((marker) . -169) 467 (t 21934 9875 0 0) nil ("<<<<<<< HEAD
=======
" . 298) ((marker . 326) . -21) ((marker . 326) . -21) ((marker) . -7) ((marker . 311) . -13) ((marker . 311) . -13) ((marker) . -21) ((marker) . -21) 319 nil ("      user:
>>>>>>> de50cd7... finish AuthViewResource ~ DimensionResource
" . 488) ((marker . 1586) . -12) ((marker . 1586) . -12) ((marker . 1540) . -75) ((marker . 1540) . -75) ((marker . 298) . -75) ((marker) . -75) ((marker) . -75) 563 nil (nil rear-nonsticky nil 575 . 576) (nil fontified nil 563 . 576) (563 . 576) nil ("
" . 311) ((marker . 765) . -1) ((marker . 765) . -1) ((marker) . -1) nil ("      brand:" . 311) (t 21934 9798 0 0) nil (298 . 332) nil ("<<<<<<< HEAD
      brand:
=======
" . 298) ((marker) . -7) ((marker . 961) . -13) ((marker . 961) . -13) ((marker . 765) . -26) ((marker . 765) . -26) ((marker . 746) . -34) ((marker . 746) . -34) ((marker) . -34) 332 (t 21934 9798 0 0) nil (298 . 332) nil ("<<<<<<< HEAD
      brand:
=======
" . 298) ((marker . 1414) . -13) ((marker . 1414) . -13) ((marker . 1393) . -26) ((marker . 1393) . -26) ((marker . 1371) . -34) ((marker . 1371) . -34) ((marker) . -7) ((marker) . -34) ((marker) . -34) 332 (t 21934 9798 0 0)))
